#!/bin/bash
set -e
set -o pipefail

if [[ ! -z "$TOKEN" ]]; then
	GITHUB_TOKEN=$TOKEN
fi

if [[ -z "$GITHUB_TOKEN" ]]; then
	echo "Set the GITHUB_TOKEN env variable."
	exit 1
fi

if [[ -z "$GITHUB_REPOSITORY" ]]; then
	echo "Set the GITHUB_REPOSITORY env variable."
	exit 1
fi

URI=https://api.github.com
API_VERSION=v3
API_HEADER="Accept: application/vnd.github.${API_VERSION}+json"
AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"
MILESTONE="v1.15"

main(){
	action=$(jq --raw-output .action "$GITHUB_EVENT_PATH")
	merged=$(jq --raw-output .pull_request.merged "$GITHUB_EVENT_PATH")

	echo "DEBUG -> action: $action merged: $merged"

	if [[ "$action" == "closed" ]] && [[ "$merged" == "true" ]] ; then
		# check if milestone is applied
        owner=$(jq --raw-output .pull_request.head.repo.owner.login "$GITHUB_EVENT_PATH")
        repo=$(jq --raw-output .pull_request.head.repo.name "$GITHUB_EVENT_PATH")
        pr_number=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")
        is_milestoned=$(
                curl -XGET -sSL \
                    -H "${AUTH_HEADER}" \
                    -H "${API_HEADER}" \
                    "${URI}/repos/${owner}/${repo}/issues/${pr_number}" | jq .milestone.number
            )
        if [[ "$is_milestoned" != NULL ]] ; then

            echo "Applying milestone ${MILESTONE} for ${owner}/${repo}/pr/${pr_number}..."
